### ISSUE TITLE
Getting 401 unauthorized response when calling roomdescription/save

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#25]
I am calling the following URL:

https://api.dezrez.com/api/roomdescription/save?agencyID=131

With the following data:

{"Name":"Kitchen","PropertyId":"319401","Rooms":[{"Name":"Kitchen","Text":"Cras ultricies ligula sed magna dictum porta. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Proin eget tortor risus. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Donec rutrum congue leo eget malesuada. Nulla porttitor accumsan tincidunt. Proin eget tortor risus. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Pellentesque in ipsum id orci porta dapibus."}],"ForceUpdate":true}

Getting the following 401 response:

{"Message":"Authorization has been denied for this request."}

When I've had this issue previously it's been due to the scope of my oauth token. My current scope is:

impersonate_web_user property_write property_read event_read event_write people_read people_write document_write document_read

**Comment by marc-harry** [comment]
Hi @geoffs3310,

We have identified the issue with this endpoint returning error 401. It has been fixed and is awaiting deployment, it will be pushed to the UAT environment within the next hour.

Cheers,
Marc

**Comment by tuscan88** [comment]
Thanks and when will that get propagated to live?

**Comment by tuscan88** [comment]
Still getting the following 401 response for this method in live:

{"Message":"Authorization has been denied for this request."}

Do you know when the fix you applied will in the live environment?

**Comment by marc-harry** [comment]
This issue will be pushed to live in the next release, I cannot specify when that will be but would recommend using the UAT environment where the fix for this particular endpoint should already be available.
